window.resumeData = {
  "files": {
    "about.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# Aaditya H Chattankatil",
        "",
        "**Software Engineer** | Distributed Systems | Python | Node.js | AWS | APIs",
        "",
        "- Phone: +91 9619654093",
        "- Email: aadityahemant24@gmail.com",
        "- LinkedIn: [linkedin.com/in/aaditya-hemant](https://linkedin.com/in/aaditya-hemant)",
        "- Location: Pune, India",
        "",
        "## Summary",
        "",
        "Software Engineer with experience building distributed systems, event-driven platforms, and developer tooling. Focused on backend architecture, cloud infrastructure, and system reliability.",
        "",
        "## Certifications",
        "",
        "- **AWS Certified Cloud Practitioner** — June 2022 (Amazon Web Services)"
      ],
      "html": "<h1>Aaditya H Chattankatil</h1>\n<p><strong>Software Engineer</strong> | Distributed Systems | Python | Node.js | AWS | APIs</p>\n<ul>\n<li>Phone: +91 9619654093</li>\n<li>Email: <a href=\"mailto:aadityahemant24@gmail.com\">aadityahemant24@gmail.com</a></li>\n<li>LinkedIn: <a href=\"https://linkedin.com/in/aaditya-hemant\">linkedin.com/in/aaditya-hemant</a></li>\n<li>Location: Pune, India</li>\n</ul>\n<h2>Summary</h2>\n<p>Software Engineer with experience building distributed systems, event-driven platforms, and developer tooling. Focused on backend architecture, cloud infrastructure, and system reliability.</p>\n<h2>Certifications</h2>\n<ul>\n<li><strong>AWS Certified Cloud Practitioner</strong> — June 2022 (Amazon Web Services)</li>\n</ul>\n",
      "terminal": [
        "> loading profile...",
        "> status: online",
        "",
        "$ whoami",
        "aaditya-hemant",
        "",
        "$ pwd",
        "/resume/software-engineer"
      ]
    },
    "experience/bajaj-finserv.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# Bajaj Finserv",
        "",
        "## Senior Software Engineer",
        "**Jan 2025 – Present** | Pune, India",
        "",
        "- **Distributed Cache Management Platform:** Designed and led development of an event-driven operational workflow platform using AWS Lambda, SQS, and Step Functions to automate cache management across distributed systems. Built governance controls that detected restricted-content URL categories and enforced approval-based cache purge workflows through automated email notifications and audit tracking. Reduced manual operational effort by 99%, improved deployment reliability, and eliminated 4+ hours of release-time coordination across teams managing 200K+ live pages.",
        "- **CLI & Workflow Automation:** Built custom CLI tooling and workflow automation to coordinate AI agent handoffs across isolated Git worktrees, enabling parallel development workflows, reducing context-switching overhead, and accelerating feature execution and prototyping by 40%.",
        "- **CDN Content Delivery (NetStorage):** Implemented Akamai NetStorage-based deployment workflows to serve static assets directly from CDN, reducing load on AEM infrastructure and improving stability during high-traffic releases.",
        "",
        "---",
        "",
        "## Software Engineer",
        "**Jan 2023 – Jan 2025** | Pune, India",
        "",
        "- **SSO Integration:** Designed and implemented secure Single Sign-On (SSO) across 3 partner applications using JWT and OAuth, improving user experience by eliminating repeated logins.",
        "- **Scalable Backend APIs:** Developed high-performance REST APIs using Node.js, handling 20M+ daily requests and supporting 50M+ monthly users. Used SQL, Redis, Elasticsearch, MongoDB, and AWS S3 to build scalable and efficient backend systems.",
        "- **Logging & Observability (ELK):** Set up centralized logging using Elasticsearch, Logstash, and Kibana (ELK), enabling structured log monitoring and faster debugging of production issues."
      ],
      "html": "<h1>Bajaj Finserv</h1>\n<h2>Senior Software Engineer</h2>\n<p><strong>Jan 2025 – Present</strong> | Pune, India</p>\n<ul>\n<li><strong>Distributed Cache Management Platform:</strong> Designed and led development of an event-driven operational workflow platform using AWS Lambda, SQS, and Step Functions to automate cache management across distributed systems. Built governance controls that detected restricted-content URL categories and enforced approval-based cache purge workflows through automated email notifications and audit tracking. Reduced manual operational effort by 99%, improved deployment reliability, and eliminated 4+ hours of release-time coordination across teams managing 200K+ live pages.</li>\n<li><strong>CLI &amp; Workflow Automation:</strong> Built custom CLI tooling and workflow automation to coordinate AI agent handoffs across isolated Git worktrees, enabling parallel development workflows, reducing context-switching overhead, and accelerating feature execution and prototyping by 40%.</li>\n<li><strong>CDN Content Delivery (NetStorage):</strong> Implemented Akamai NetStorage-based deployment workflows to serve static assets directly from CDN, reducing load on AEM infrastructure and improving stability during high-traffic releases.</li>\n</ul>\n<hr>\n<h2>Software Engineer</h2>\n<p><strong>Jan 2023 – Jan 2025</strong> | Pune, India</p>\n<ul>\n<li><strong>SSO Integration:</strong> Designed and implemented secure Single Sign-On (SSO) across 3 partner applications using JWT and OAuth, improving user experience by eliminating repeated logins.</li>\n<li><strong>Scalable Backend APIs:</strong> Developed high-performance REST APIs using Node.js, handling 20M+ daily requests and supporting 50M+ monthly users. Used SQL, Redis, Elasticsearch, MongoDB, and AWS S3 to build scalable and efficient backend systems.</li>\n<li><strong>Logging &amp; Observability (ELK):</strong> Set up centralized logging using Elasticsearch, Logstash, and Kibana (ELK), enabling structured log monitoring and faster debugging of production issues.</li>\n</ul>\n",
      "terminal": [
        "$ git log --oneline",
        "a81f203 senior-software-engineer at Bajaj Finserv",
        "4c927be shipped cache management platform v2",
        "d79a114 software-engineer at Bajaj Finserv",
        "13fd982 sso-integration across partner apps",
        "",
        "career history loaded"
      ]
    },
    "experience/atsuya.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# Atsuya Technologies Ltd.",
        "",
        "## Machine Learning Intern",
        "**Oct 2021 – Dec 2021** | Chennai, India",
        "",
        "- Developed and evaluated machine learning models for time-series forecasting and anomaly detection.",
        "- Generated alerts based on detected anomalies and integrated them into production workflows."
      ],
      "html": "<h1>Atsuya Technologies Ltd.</h1>\n<h2>Machine Learning Intern</h2>\n<p><strong>Oct 2021 – Dec 2021</strong> | Chennai, India</p>\n<ul>\n<li>Developed and evaluated machine learning models for time-series forecasting and anomaly detection.</li>\n<li>Generated alerts based on detected anomalies and integrated them into production workflows.</li>\n</ul>\n",
      "terminal": [
        "$ cat experience/atsuya.md",
        "ml-intern at Atsuya Technologies",
        "time-series forecasting & anomaly detection",
        "",
        "internship completed dec 2021"
      ]
    },
    "education.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# Education",
        "",
        "## Vellore Institute of Technology, Chennai",
        "",
        "**Bachelor of Technology — Computer Science (Specialization in AI & Machine Learning)**",
        "",
        "**2019 – 2023** | Chennai, India",
        "",
        "- CGPA: **9.01 / 10**",
        "",
        "---",
        "",
        "## Shri Tikamdas Puroshottam Bhatia College of Science",
        "",
        "**Higher Secondary Certificate (HSC) — Science**",
        "",
        "**2017 – 2019**",
        "",
        "---",
        "",
        "## St. Joseph's High School",
        "",
        "**Secondary School Certificate (SSC)**",
        "",
        "**2017**"
      ],
      "html": "<h1>Education</h1>\n<h2>Vellore Institute of Technology, Chennai</h2>\n<p><strong>Bachelor of Technology — Computer Science (Specialization in AI &amp; Machine Learning)</strong></p>\n<p><strong>2019 – 2023</strong> | Chennai, India</p>\n<ul>\n<li>CGPA: <strong>9.01 / 10</strong></li>\n</ul>\n<hr>\n<h2>Shri Tikamdas Puroshottam Bhatia College of Science</h2>\n<p><strong>Higher Secondary Certificate (HSC) — Science</strong></p>\n<p><strong>2017 – 2019</strong></p>\n<hr>\n<h2>St. Joseph&#39;s High School</h2>\n<p><strong>Secondary School Certificate (SSC)</strong></p>\n<p><strong>2017</strong></p>\n",
      "terminal": [
        "$ cat education.md",
        "VIT Chennai — BTech CSE (AI & ML), CGPA 9.01",
        "Bhatia College — HSC Science",
        "St. Joseph's — SSC",
        "",
        "education summary loaded"
      ]
    },
    "projects/cache-platform.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# Cache Management Platform",
        "",
        "Event-driven operational workflow platform to automate cache management across distributed systems.",
        "",
        "## Stack",
        "",
        "AWS Lambda, SQS, Step Functions, Akamai CDN, NetStorage, Node.js",
        "",
        "## Impact",
        "",
        "- 99% reduction in manual operational effort",
        "- 200K+ live pages managed",
        "- 4+ hours of release-time coordination eliminated per deployment",
        "",
        "",
        "---",
        "",
        "# Architecture",
        "# Architecture",
        "",
        "## Event-Driven Cache Governance",
        "",
        "```",
        "URL Update → SQS Queue → Lambda (detect restricted content)",
        "                           │",
        "                           ▼",
        "                    Step Function (approval workflow)",
        "                           │",
        "               ┌───────────┴───────────┐",
        "               ▼                       ▼",
        "          Auto-Approve          Email Notification",
        "               │                       │",
        "               ▼                       ▼",
        "          Purge Cache          Await Manual Approval",
        "                                       │",
        "                                       ▼",
        "                                  Purge Cache",
        "```",
        "",
        "## Components",
        "",
        "- **Content Detector** — AWS Lambda that inspects URL categories and flags restricted content",
        "- **Approval Orchestrator** — Step Function state machine managing approval branching",
        "- **Notification Service** — Automated email notifications via SES with audit tracking",
        "- **Cache Purge Executor** — Lambda integration with Akamai CCU API for cache invalidation",
        "",
        "## Governance",
        "",
        "- Restricted-content URL categories detected at ingestion time",
        "- Approval-based workflows enforced via email-based approval loops",
        "- Full audit trail for all purge operations",
        "",
        "",
        "---",
        "",
        "# Metrics",
        "{\n  \"operationalEffortReduction\": \"99%\",\n  \"livePagesManaged\": 200000,\n  \"releaseCoordinationTimeSaved\": \"4+ hours\",\n  \"teamsImpacted\": \"cross-team coordination\",\n  \"servicesUsed\": [\n    \"AWS Lambda\",\n    \"Amazon SQS\",\n    \"AWS Step Functions\",\n    \"Akamai CDN\",\n    \"Akamai NetStorage\"\n  ]\n}"
      ],
      "html": "<h1>Cache Management Platform</h1>\n<p>Event-driven operational workflow platform to automate cache management across distributed systems.</p>\n<h2>Stack</h2>\n<p>AWS Lambda, SQS, Step Functions, Akamai CDN, NetStorage, Node.js</p>\n<h2>Impact</h2>\n<ul>\n<li>99% reduction in manual operational effort</li>\n<li>200K+ live pages managed</li>\n<li>4+ hours of release-time coordination eliminated per deployment</li>\n</ul>\n<hr>\n<h1>Architecture</h1>\n<h1>Architecture</h1>\n<h2>Event-Driven Cache Governance</h2>\n<pre><code>URL Update → SQS Queue → Lambda (detect restricted content)\n                           │\n                           ▼\n                    Step Function (approval workflow)\n                           │\n               ┌───────────┴───────────┐\n               ▼                       ▼\n          Auto-Approve          Email Notification\n               │                       │\n               ▼                       ▼\n          Purge Cache          Await Manual Approval\n                                       │\n                                       ▼\n                                  Purge Cache\n</code></pre>\n<h2>Components</h2>\n<ul>\n<li><strong>Content Detector</strong> — AWS Lambda that inspects URL categories and flags restricted content</li>\n<li><strong>Approval Orchestrator</strong> — Step Function state machine managing approval branching</li>\n<li><strong>Notification Service</strong> — Automated email notifications via SES with audit tracking</li>\n<li><strong>Cache Purge Executor</strong> — Lambda integration with Akamai CCU API for cache invalidation</li>\n</ul>\n<h2>Governance</h2>\n<ul>\n<li>Restricted-content URL categories detected at ingestion time</li>\n<li>Approval-based workflows enforced via email-based approval loops</li>\n<li>Full audit trail for all purge operations</li>\n</ul>\n<hr>\n<h1>Metrics</h1>\n<p>{<br>  &quot;operationalEffortReduction&quot;: &quot;99%&quot;,<br>  &quot;livePagesManaged&quot;: 200000,<br>  &quot;releaseCoordinationTimeSaved&quot;: &quot;4+ hours&quot;,<br>  &quot;teamsImpacted&quot;: &quot;cross-team coordination&quot;,<br>  &quot;servicesUsed&quot;: [<br>    &quot;AWS Lambda&quot;,<br>    &quot;Amazon SQS&quot;,<br>    &quot;AWS Step Functions&quot;,<br>    &quot;Akamai CDN&quot;,<br>    &quot;Akamai NetStorage&quot;<br>  ]<br>}</p>\n",
      "terminal": [
        "$ npm run build -- cache-management-platform",
        "compile... ok",
        "validate... ok",
        "deploy... ok",
        "",
        "stack: aws-lambda sqs step-functions akamai nodejs",
        "result: 99% reduction in manual effort, 200K+ live pages"
      ]
    },
    "projects/ai-cli.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# AI CLI",
        "",
        "Custom CLI tooling and workflow automation to coordinate AI agent handoffs across isolated Git worktrees.",
        "",
        "## Stack",
        "",
        "Python, Node.js, Git, GitHub Actions, Ollama, Claude, Copilot CLI",
        "",
        "## Impact",
        "",
        "- 40% faster feature execution and prototyping",
        "- Reduced context-switching overhead for AI-assisted development",
        "- Enabled parallel development workflows across isolated worktrees",
        ""
      ],
      "html": "<h1>AI CLI</h1>\n<p>Custom CLI tooling and workflow automation to coordinate AI agent handoffs across isolated Git worktrees.</p>\n<h2>Stack</h2>\n<p>Python, Node.js, Git, GitHub Actions, Ollama, Claude, Copilot CLI</p>\n<h2>Impact</h2>\n<ul>\n<li>40% faster feature execution and prototyping</li>\n<li>Reduced context-switching overhead for AI-assisted development</li>\n<li>Enabled parallel development workflows across isolated worktrees</li>\n</ul>\n",
      "terminal": [
        "$ npm run build -- ai-cli",
        "compile... ok",
        "validate... ok",
        "deploy... ok",
        "",
        "stack: python nodejs git github-actions ollama claude",
        "result: 40% faster prototyping, parallel worktree workflows"
      ]
    },
    "projects/cms-migration.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# CMS Migration",
        "",
        "Migrated static asset delivery from AEM infrastructure to Akamai NetStorage CDN.",
        "",
        "## Stack",
        "",
        "Akamai CDN, NetStorage, AEM Dispatcher, AWS Lambda",
        "",
        "## Impact",
        "",
        "- Reduced load on AEM infrastructure",
        "- Improved stability during high-traffic releases",
        "- Static assets served directly from CDN edge",
        ""
      ],
      "html": "<h1>CMS Migration</h1>\n<p>Migrated static asset delivery from AEM infrastructure to Akamai NetStorage CDN.</p>\n<h2>Stack</h2>\n<p>Akamai CDN, NetStorage, AEM Dispatcher, AWS Lambda</p>\n<h2>Impact</h2>\n<ul>\n<li>Reduced load on AEM infrastructure</li>\n<li>Improved stability during high-traffic releases</li>\n<li>Static assets served directly from CDN edge</li>\n</ul>\n",
      "terminal": [
        "$ npm run build -- cms-migration",
        "compile... ok",
        "validate... ok",
        "deploy... ok",
        "",
        "stack: akamai netstorage aem-dispatcher lambda",
        "result: reduced AEM load, improved release stability"
      ]
    },
    "projects/run-club.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# Out of Office Run Club",
        "",
        "Two-page website for a Sunday morning social running community based in Kharadi, Pune.",
        "",
        "## Stack",
        "",
        "Next.js 14 (App Router), TypeScript, Tailwind CSS, Netlify",
        "",
        "## Pages",
        "",
        "- **Home** — Hero, next-run bib card, club intro, photo grid, WhatsApp CTA",
        "- **Schedule** — Run calendar with completed/upcoming runs, current route info",
        "",
        "## Impact",
        "",
        "- 40+ runners at launch",
        "- Bi-weekly 5K social runs",
        "- Deployed on Netlify with Next.js runtime",
        "",
        "## Live Site",
        "",
        "https://out-of-office-run-club.netlify.app",
        ""
      ],
      "html": "<h1>Out of Office Run Club</h1>\n<p>Two-page website for a Sunday morning social running community based in Kharadi, Pune.</p>\n<h2>Stack</h2>\n<p>Next.js 14 (App Router), TypeScript, Tailwind CSS, Netlify</p>\n<h2>Pages</h2>\n<ul>\n<li><strong>Home</strong> — Hero, next-run bib card, club intro, photo grid, WhatsApp CTA</li>\n<li><strong>Schedule</strong> — Run calendar with completed/upcoming runs, current route info</li>\n</ul>\n<h2>Impact</h2>\n<ul>\n<li>40+ runners at launch</li>\n<li>Bi-weekly 5K social runs</li>\n<li>Deployed on Netlify with Next.js runtime</li>\n</ul>\n<h2>Live Site</h2>\n<p><a href=\"https://out-of-office-run-club.netlify.app\">https://out-of-office-run-club.netlify.app</a></p>\n",
      "terminal": [
        "$ npm run build -- run-club",
        "compile... ok",
        "validate... ok",
        "deploy... ok",
        "",
        "stack: nextjs typescript tailwindcss netlify",
        "result: 40+ runners at launch, bi-weekly social runs"
      ]
    },
    "skills.json": {
      "type": "JSON",
      "language": "JSON",
      "code": [
        "{",
        "  \"languages\": [",
        "    \"Python\",",
        "    \"JavaScript\",",
        "    \"TypeScript\",",
        "    \"Go\",",
        "    \"SQL\"",
        "  ],",
        "  \"frameworks\": [",
        "    \"Node.js\",",
        "    \"Express.js\"",
        "  ],",
        "  \"apis\": [",
        "    \"REST APIs\",",
        "    \"Microservices\",",
        "    \"Authentication & SSO\"",
        "  ],",
        "  \"auth\": [",
        "    \"JWT\",",
        "    \"OAuth\"",
        "  ],",
        "  \"aws\": [",
        "    \"Lambda\",",
        "    \"Step Functions\",",
        "    \"SQS\",",
        "    \"API Gateway\",",
        "    \"S3\"",
        "  ],",
        "  \"azure\": [",
        "    \"Functions\",",
        "    \"Queues\",",
        "    \"API Management\"",
        "  ],",
        "  \"caching\": [",
        "    \"CDN Caching\",",
        "    \"Cache Invalidation Strategies\"",
        "  ],",
        "  \"infrastructure\": [",
        "    \"Akamai CDN\",",
        "    \"NetStorage\",",
        "    \"AEM Dispatcher\"",
        "  ],",
        "  \"observability\": [",
        "    \"ELK Stack\",",
        "    \"New Relic\"",
        "  ],",
        "  \"ciCd\": [",
        "    \"GitHub Actions\"",
        "  ],",
        "  \"specializations\": [",
        "    \"Machine Learning\",",
        "    \"Time-Series Forecasting\",",
        "    \"Anomaly Detection\"",
        "  ],",
        "  \"tools\": [",
        "    \"Claude\",",
        "    \"Ollama\",",
        "    \"Copilot CLI\"",
        "  ],",
        "  \"applications\": [",
        "    \"AI Agent Handoffs\",",
        "    \"Predictive Alerting\",",
        "    \"Workflow Automation\"",
        "  ]",
        "}"
      ],
      "terminal": [
        "$ jq '.cloud.aws' skills.json",
        "[\"Lambda\", \"Step Functions\", \"SQS\", \"API Gateway\", \"S3\"]",
        "",
        "$ jq '.backend.languages' skills.json",
        "[\"Python\", \"JavaScript\", \"TypeScript\", \"Go\", \"SQL\"]"
      ]
    },
    "contact.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# Contact",
        "",
        "Email: aadityahemant24@gmail.com",
        "LinkedIn: https://linkedin.com/in/aaditya-hemant",
        "GitHub: https://github.com/aaditya-hemant",
        "Resume PDF: ./resume.pdf",
        "",
        "Open to software engineering, backend, platform, and distributed systems roles."
      ],
      "html": "<h1>Contact</h1>\n<p>Email: <a href=\"mailto:aadityahemant24@gmail.com\">aadityahemant24@gmail.com</a><br>LinkedIn: <a href=\"https://linkedin.com/in/aaditya-hemant\">https://linkedin.com/in/aaditya-hemant</a><br>GitHub: <a href=\"https://github.com/aaditya-hemant\">https://github.com/aaditya-hemant</a><br>Resume PDF: ./resume.pdf</p>\n<p>Open to software engineering, backend, platform, and distributed systems roles.</p>\n",
      "terminal": [
        "$ curl /api/contact",
        "HTTP/1.1 200 OK",
        "content-type: application/json",
        "",
        "{",
        "  \"email\": \"aadityahemant24@gmail.com\",",
        "  \"linkedin\": \"https://linkedin.com/in/aaditya-hemant\",",
        "  \"github\": \"https://github.com/aaditya-hemant\"",
        "}"
      ]
    }
  },
  "commands": {
    "whoami": "about.md",
    "cat about.md": "about.md",
    "git log --oneline": "experience/bajaj-finserv.md",
    "cat experience/bajaj-finserv.md": "experience/bajaj-finserv.md",
    "cat experience/atsuya.md": "experience/atsuya.md",
    "cat education.md": "education.md",
    "ls projects/": "projects/cache-platform.md",
    "cat projects/cache-platform.md": "projects/cache-platform.md",
    "cat projects/ai-cli.md": "projects/ai-cli.md",
    "cat projects/cms-migration.md": "projects/cms-migration.md",
    "cat skills.json": "skills.json",
    "cat contact.md": "contact.md",
    "cat resume.pdf": "contact.md",
    "cat projects/run-club.md": "projects/run-club.md"
  }
};