window.resumeData = {
  "files": {
    "about.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# Aaditya H Chattankatil",
        "",
        "**Backend Software Engineer** | Platform & Cloud Engineering",
        "",
        "- Phone: +91 9619654093",
        "- Email: aadityahemant24@gmail.com",
        "- LinkedIn: [linkedin.com/in/aaditya-hemant](https://linkedin.com/in/aaditya-hemant)",
        "- GitHub: [github.com/aaditya-hemant](https://github.com/aaditya-hemant)",
        "- Location: Pune, India",
        "- [Download Resume](./resume.pdf)",
        "",
        "## Summary",
        "",
        "Backend Software Engineer specializing in Platform & Cloud Engineering, with 3+ years of experience designing scalable backend systems, distributed platforms, and cloud-native applications.",
        "",
        "Experienced in building high-throughput REST APIs serving 20M+ daily requests, configuration-driven platforms, event-driven workflows, and operational tooling that automate complex enterprise processes. My work spans serverless architectures, workflow orchestration, content platforms, cache management, and internal developer productivity.",
        "",
        "I enjoy designing reliable systems that simplify operations, scale gracefully, and become foundational platforms for engineering teams.",
        "",
        "## Core Expertise",
        "",
        "- Distributed Systems",
        "- Large-scale REST APIs",
        "- Serverless Architectures",
        "- Event-Driven Systems",
        "- Workflow Orchestration",
        "- Platform Engineering",
        "- Enterprise Integrations",
        "- Operational Tooling & Automation",
        "",
        "## Certifications",
        "",
        "- **AWS Certified Cloud Practitioner** — June 2022 (Amazon Web Services)"
      ],
      "html": "<h1>Aaditya H Chattankatil</h1>\n<p><strong>Backend Software Engineer</strong> | Platform &amp; Cloud Engineering</p>\n<ul>\n<li>Phone: +91 9619654093</li>\n<li>Email: <a href=\"mailto:aadityahemant24@gmail.com\">aadityahemant24@gmail.com</a></li>\n<li>LinkedIn: <a href=\"https://linkedin.com/in/aaditya-hemant\">linkedin.com/in/aaditya-hemant</a></li>\n<li>GitHub: <a href=\"https://github.com/aaditya-hemant\">github.com/aaditya-hemant</a></li>\n<li>Location: Pune, India</li>\n<li><a href=\"./resume.pdf\">Download Resume</a></li>\n</ul>\n<h2>Summary</h2>\n<p>Backend Software Engineer specializing in Platform &amp; Cloud Engineering, with 3+ years of experience designing scalable backend systems, distributed platforms, and cloud-native applications.</p>\n<p>Experienced in building high-throughput REST APIs serving 20M+ daily requests, configuration-driven platforms, event-driven workflows, and operational tooling that automate complex enterprise processes. My work spans serverless architectures, workflow orchestration, content platforms, cache management, and internal developer productivity.</p>\n<p>I enjoy designing reliable systems that simplify operations, scale gracefully, and become foundational platforms for engineering teams.</p>\n<h2>Core Expertise</h2>\n<ul>\n<li>Distributed Systems</li>\n<li>Large-scale REST APIs</li>\n<li>Serverless Architectures</li>\n<li>Event-Driven Systems</li>\n<li>Workflow Orchestration</li>\n<li>Platform Engineering</li>\n<li>Enterprise Integrations</li>\n<li>Operational Tooling &amp; Automation</li>\n</ul>\n<h2>Certifications</h2>\n<ul>\n<li><strong>AWS Certified Cloud Practitioner</strong> — June 2022 (Amazon Web Services)</li>\n</ul>\n",
      "terminal": [
        "> loading profile...",
        "> status: online",
        "",
        "$ whoami",
        "aaditya-hemant",
        "",
        "$ pwd",
        "/resume/software-engineer"
      ]
    },
    "experience/bajaj-finserv.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# Bajaj Finserv",
        "",
        "## Senior Software Engineer",
        "**Jan 2025 – Present** | Pune, India",
        "",
        "- **CMS Migration Engine:** Architected and developed a configuration-driven migration platform to migrate 120K+ AEM pages into a modern headless CMS, orchestrating AWS Lambda, SQS, Step Functions, and S3 to support 98 reusable components through runtime-selectable JSON mappings, rule-based template detection, automated retries, and health-aware batch ingestion.",
        "- **Distributed Cache Management Platform:** Designed and led development of an event-driven operational workflow platform using AWS Lambda, SQS, and Step Functions to automate cache management across distributed systems. Built governance controls that detected restricted-content URL categories and enforced approval-based cache purge workflows through automated email notifications and audit tracking. Reduced manual operational effort by 99%, improved deployment reliability, and eliminated 4+ hours of release-time coordination across teams managing 200K+ live pages.",
        "- **CLI & Workflow Automation:** Built custom CLI tooling and workflow automation to coordinate AI agent handoffs across isolated Git worktrees, enabling parallel development workflows, reducing context-switching overhead, and accelerating feature execution and prototyping by 40%.",
        "- **CDN Content Delivery (NetStorage):** Implemented Akamai NetStorage-based deployment workflows to serve static assets directly from CDN, reducing load on AEM infrastructure and improving stability during high-traffic releases.",
        "",
        "",
        "---",
        "",
        "## Software Engineer",
        "**Jan 2023 – Jan 2025** | Pune, India",
        "",
        "- **SSO Integration:** Designed and implemented secure Single Sign-On (SSO) across 3 partner applications using JWT and OAuth, improving user experience by eliminating repeated logins.",
        "- **Scalable Backend APIs:** Developed high-performance REST APIs using Node.js, handling 20M+ daily requests and supporting 50M+ monthly users. Used SQL, Redis, Elasticsearch, MongoDB, and AWS S3 to build scalable and efficient backend systems.",
        "- **Logging & Observability (ELK):** Set up centralized logging using Elasticsearch, Logstash, and Kibana (ELK), enabling structured log monitoring and faster debugging of production issues."
      ],
      "html": "<h1>Bajaj Finserv</h1>\n<h2>Senior Software Engineer</h2>\n<p><strong>Jan 2025 – Present</strong> | Pune, India</p>\n<ul>\n<li><strong>CMS Migration Engine:</strong> Architected and developed a configuration-driven migration platform to migrate 120K+ AEM pages into a modern headless CMS, orchestrating AWS Lambda, SQS, Step Functions, and S3 to support 98 reusable components through runtime-selectable JSON mappings, rule-based template detection, automated retries, and health-aware batch ingestion.</li>\n<li><strong>Distributed Cache Management Platform:</strong> Designed and led development of an event-driven operational workflow platform using AWS Lambda, SQS, and Step Functions to automate cache management across distributed systems. Built governance controls that detected restricted-content URL categories and enforced approval-based cache purge workflows through automated email notifications and audit tracking. Reduced manual operational effort by 99%, improved deployment reliability, and eliminated 4+ hours of release-time coordination across teams managing 200K+ live pages.</li>\n<li><strong>CLI &amp; Workflow Automation:</strong> Built custom CLI tooling and workflow automation to coordinate AI agent handoffs across isolated Git worktrees, enabling parallel development workflows, reducing context-switching overhead, and accelerating feature execution and prototyping by 40%.</li>\n<li><strong>CDN Content Delivery (NetStorage):</strong> Implemented Akamai NetStorage-based deployment workflows to serve static assets directly from CDN, reducing load on AEM infrastructure and improving stability during high-traffic releases.</li>\n</ul>\n<hr>\n<h2>Software Engineer</h2>\n<p><strong>Jan 2023 – Jan 2025</strong> | Pune, India</p>\n<ul>\n<li><strong>SSO Integration:</strong> Designed and implemented secure Single Sign-On (SSO) across 3 partner applications using JWT and OAuth, improving user experience by eliminating repeated logins.</li>\n<li><strong>Scalable Backend APIs:</strong> Developed high-performance REST APIs using Node.js, handling 20M+ daily requests and supporting 50M+ monthly users. Used SQL, Redis, Elasticsearch, MongoDB, and AWS S3 to build scalable and efficient backend systems.</li>\n<li><strong>Logging &amp; Observability (ELK):</strong> Set up centralized logging using Elasticsearch, Logstash, and Kibana (ELK), enabling structured log monitoring and faster debugging of production issues.</li>\n</ul>\n",
      "terminal": [
        "$ git log --oneline",
        "a81f203 senior-software-engineer at Bajaj Finserv",
        "4c927be shipped cache management platform v2",
        "d79a114 software-engineer at Bajaj Finserv",
        "13fd982 sso-integration across partner apps",
        "",
        "career history loaded"
      ]
    },
    "experience/atsuya.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# Atsuya Technologies Ltd.",
        "",
        "## Machine Learning Intern",
        "**Oct 2021 – Dec 2021** | Chennai, India",
        "",
        "- Developed and evaluated machine learning models for time-series forecasting and anomaly detection.",
        "- Generated alerts based on detected anomalies and integrated them into production workflows."
      ],
      "html": "<h1>Atsuya Technologies Ltd.</h1>\n<h2>Machine Learning Intern</h2>\n<p><strong>Oct 2021 – Dec 2021</strong> | Chennai, India</p>\n<ul>\n<li>Developed and evaluated machine learning models for time-series forecasting and anomaly detection.</li>\n<li>Generated alerts based on detected anomalies and integrated them into production workflows.</li>\n</ul>\n",
      "terminal": [
        "$ cat experience/atsuya.md",
        "ml-intern at Atsuya Technologies",
        "time-series forecasting & anomaly detection",
        "",
        "internship completed dec 2021"
      ]
    },
    "education.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# Education",
        "",
        "## Vellore Institute of Technology, Chennai",
        "",
        "**Bachelor of Technology — Computer Science (Specialization in AI & Machine Learning)**",
        "",
        "**2019 – 2023** | Chennai, India",
        "",
        "- CGPA: **9.01 / 10**",
        "",
        "---",
        "",
        "## Shri Tikamdas Puroshottam Bhatia College of Science",
        "",
        "**Higher Secondary Certificate (HSC) — Science**",
        "",
        "**2017 – 2019**",
        "",
        "---",
        "",
        "## St. Joseph's High School",
        "",
        "**Secondary School Certificate (SSC)**",
        "",
        "**2017**"
      ],
      "html": "<h1>Education</h1>\n<h2>Vellore Institute of Technology, Chennai</h2>\n<p><strong>Bachelor of Technology — Computer Science (Specialization in AI &amp; Machine Learning)</strong></p>\n<p><strong>2019 – 2023</strong> | Chennai, India</p>\n<ul>\n<li>CGPA: <strong>9.01 / 10</strong></li>\n</ul>\n<hr>\n<h2>Shri Tikamdas Puroshottam Bhatia College of Science</h2>\n<p><strong>Higher Secondary Certificate (HSC) — Science</strong></p>\n<p><strong>2017 – 2019</strong></p>\n<hr>\n<h2>St. Joseph&#39;s High School</h2>\n<p><strong>Secondary School Certificate (SSC)</strong></p>\n<p><strong>2017</strong></p>\n",
      "terminal": [
        "$ cat education.md",
        "VIT Chennai — BTech CSE (AI & ML), CGPA 9.01",
        "Bhatia College — HSC Science",
        "St. Joseph's — SSC",
        "",
        "education summary loaded"
      ]
    },
    "projects/cache-platform.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# Cache Operations Platform",
        "",
        "## Overview",
        "",
        "Designed and built an enterprise platform to orchestrate cache invalidation and content delivery workflows across AEM, Akamai Edge, NetStorage, and Dispatcher infrastructure. The platform enables engineering and content teams to safely execute cache operations at scale through policy-driven governance, intelligent execution strategies, and automated recovery.",
        "",
        "## Key Capabilities",
        "",
        "- Self-service dashboard for cache operations",
        "- Sitemap-based URL discovery and selective cache invalidation",
        "- Bulk cache requests through Excel imports",
        "- Multi-domain and multi-site cache management",
        "- Automatic resolution of vanity URLs to dispatcher cache paths",
        "- Intelligent routing between Akamai purge and NetStorage deployment",
        "- Dispatcher cache warm-up to minimize origin traffic after invalidation",
        "- Rule-based governance with graded approval workflows",
        "- Email approvals with one-click approve/reject actions",
        "- Origin health gates preventing unsafe production operations",
        "- Safe retries with complete audit history",
        "- Elasticsearch indexing and New Relic observability",
        "",
        "## Integrations",
        "",
        "- Adobe Experience Manager (AEM)",
        "- Akamai Edge",
        "- Akamai NetStorage",
        "- Elasticsearch",
        "- New Relic",
        "- AWS Lambda",
        "- Step Functions",
        "- SQS",
        "",
        "## Architecture",
        "",
        "```",
        "User",
        "   │",
        "   ▼",
        "Cache Operations Dashboard",
        "   │",
        "   ▼",
        "Governance Engine",
        "   │",
        "   ├── Approval Workflow",
        "   ├── Policy Validation",
        "   ├── Health Gates",
        "   ▼",
        "Execution Engine",
        "   │",
        "   ├── Dispatcher Warm-up",
        "   ├── NetStorage Upload",
        "   ├── Akamai Purge",
        "   └── Safe Retries",
        "   ▼",
        "Monitoring & Audit",
        "```",
        "",
        "## Highlights",
        "",
        "- Automated enterprise cache operations across multiple production domains",
        "- Reduced manual deployment effort through intelligent workflows",
        "- Protected origin infrastructure using health-aware execution",
        "- Standardized cache management through reusable operational tooling",
        "- Built as a scalable, event-driven platform integrating multiple enterprise systems",
        ""
      ],
      "html": "<h1>Cache Operations Platform</h1>\n<h2>Overview</h2>\n<p>Designed and built an enterprise platform to orchestrate cache invalidation and content delivery workflows across AEM, Akamai Edge, NetStorage, and Dispatcher infrastructure. The platform enables engineering and content teams to safely execute cache operations at scale through policy-driven governance, intelligent execution strategies, and automated recovery.</p>\n<h2>Key Capabilities</h2>\n<ul>\n<li>Self-service dashboard for cache operations</li>\n<li>Sitemap-based URL discovery and selective cache invalidation</li>\n<li>Bulk cache requests through Excel imports</li>\n<li>Multi-domain and multi-site cache management</li>\n<li>Automatic resolution of vanity URLs to dispatcher cache paths</li>\n<li>Intelligent routing between Akamai purge and NetStorage deployment</li>\n<li>Dispatcher cache warm-up to minimize origin traffic after invalidation</li>\n<li>Rule-based governance with graded approval workflows</li>\n<li>Email approvals with one-click approve/reject actions</li>\n<li>Origin health gates preventing unsafe production operations</li>\n<li>Safe retries with complete audit history</li>\n<li>Elasticsearch indexing and New Relic observability</li>\n</ul>\n<h2>Integrations</h2>\n<ul>\n<li>Adobe Experience Manager (AEM)</li>\n<li>Akamai Edge</li>\n<li>Akamai NetStorage</li>\n<li>Elasticsearch</li>\n<li>New Relic</li>\n<li>AWS Lambda</li>\n<li>Step Functions</li>\n<li>SQS</li>\n</ul>\n<h2>Architecture</h2>\n<pre><code>User\n   │\n   ▼\nCache Operations Dashboard\n   │\n   ▼\nGovernance Engine\n   │\n   ├── Approval Workflow\n   ├── Policy Validation\n   ├── Health Gates\n   ▼\nExecution Engine\n   │\n   ├── Dispatcher Warm-up\n   ├── NetStorage Upload\n   ├── Akamai Purge\n   └── Safe Retries\n   ▼\nMonitoring &amp; Audit\n</code></pre>\n<h2>Highlights</h2>\n<ul>\n<li>Automated enterprise cache operations across multiple production domains</li>\n<li>Reduced manual deployment effort through intelligent workflows</li>\n<li>Protected origin infrastructure using health-aware execution</li>\n<li>Standardized cache management through reusable operational tooling</li>\n<li>Built as a scalable, event-driven platform integrating multiple enterprise systems</li>\n</ul>\n",
      "terminal": [
        "$ npm run build -- cache-operations-platform",
        "compile... ok",
        "validate... ok",
        "deploy... ok",
        "",
        "stack: aws-lambda step-functions sqs akamai aem elasticsearch newrelic",
        "result: automated enterprise cache ops across multiple domains"
      ]
    },
    "projects/ai-cli.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# AI CLI",
        "",
        "CLI toolchain that orchestrates AI agent handoffs across isolated Git worktrees, enabling parallel AI-assisted feature development without branch conflicts.",
        "",
        "## How it works",
        "",
        "```",
        "User task → AI CLI spawns isolated worktree",
        "                ↓",
        "         Agent A works in worktree-1",
        "         Agent B works in worktree-2  (parallel, no conflicts)",
        "                ↓",
        "         Coordinated merge → PR creation",
        "```",
        "",
        "Each AI agent gets a dedicated Git worktree — a full working copy isolated from every other agent's changes. No branch switching, no merge conflicts between agents, no context loss.",
        "",
        "## Key capabilities",
        "",
        "- **Worktree lifecycle management** — create, track, and clean up isolated worktrees per agent session",
        "- **Agent handoff protocol** — structured context files passed between agents via worktree boundaries",
        "- **Automated merge orchestration** — sequential or parallel merge strategies for multi-agent output",
        "- **Wrap-up automation** — commit squashing, branch creation, and PR generation after agent completion",
        "",
        "## Impact",
        "",
        "- 40% faster feature prototyping through parallel agent execution",
        "- Eliminated context-switching overhead — each agent starts fresh in a clean worktree",
        "- Reduced PR conflicts by isolating agent changes at the filesystem level",
        ""
      ],
      "html": "<h1>AI CLI</h1>\n<p>CLI toolchain that orchestrates AI agent handoffs across isolated Git worktrees, enabling parallel AI-assisted feature development without branch conflicts.</p>\n<h2>How it works</h2>\n<pre><code>User task → AI CLI spawns isolated worktree\n                ↓\n         Agent A works in worktree-1\n         Agent B works in worktree-2  (parallel, no conflicts)\n                ↓\n         Coordinated merge → PR creation\n</code></pre>\n<p>Each AI agent gets a dedicated Git worktree — a full working copy isolated from every other agent&#39;s changes. No branch switching, no merge conflicts between agents, no context loss.</p>\n<h2>Key capabilities</h2>\n<ul>\n<li><strong>Worktree lifecycle management</strong> — create, track, and clean up isolated worktrees per agent session</li>\n<li><strong>Agent handoff protocol</strong> — structured context files passed between agents via worktree boundaries</li>\n<li><strong>Automated merge orchestration</strong> — sequential or parallel merge strategies for multi-agent output</li>\n<li><strong>Wrap-up automation</strong> — commit squashing, branch creation, and PR generation after agent completion</li>\n</ul>\n<h2>Impact</h2>\n<ul>\n<li>40% faster feature prototyping through parallel agent execution</li>\n<li>Eliminated context-switching overhead — each agent starts fresh in a clean worktree</li>\n<li>Reduced PR conflicts by isolating agent changes at the filesystem level</li>\n</ul>\n",
      "terminal": [
        "$ npm run build -- ai-cli",
        "compile... ok",
        "validate... ok",
        "deploy... ok",
        "",
        "stack: python nodejs git github-actions ollama claude",
        "result: 40% faster prototyping, parallel worktree workflows"
      ]
    },
    "projects/content-migration.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# Content Migration Engine",
        "",
        "Designed and developed a configuration-driven migration platform to migrate content from AEM to CF360 at enterprise scale. Rather than building one-off migration scripts, the platform used runtime-selectable JSON configuration files to support different page structures, templates, and component mappings across multiple migrations.",
        "",
        "## My Ownership",
        "",
        "- End-to-end backend architecture",
        "- AWS Lambda orchestration",
        "- Amazon SQS integration",
        "- AWS Step Functions workflow",
        "- Amazon S3 configuration management",
        "- Migration APIs",
        "- Transformation engine",
        "- Status tracking",
        "- Cloud configuration (excluding VPN/security provisioning handled by DevOps)",
        "",
        "## Key Engineering Decisions",
        "",
        "### Configuration-driven migrations",
        "",
        "Migration rules were stored as JSON configuration files in S3 and selected during migration startup.",
        "",
        "This allowed:",
        "",
        "- Different migrations to reuse the same engine",
        "- Support for multiple page structures",
        "- Support for different template mappings",
        "- Reduced need for code changes",
        "",
        "### Transformation Engine",
        "",
        "Handled:",
        "",
        "- Field mapping",
        "- Component ID mapping",
        "- Nested list transformations",
        "- Rich text conversion",
        "- Page/component relationship mapping",
        "- Rule-based template detection",
        "",
        "### Scale",
        "",
        "- 120,000+ pages",
        "- 98 component types",
        "- Batch-based migration pipeline",
        "",
        "### Reliability",
        "",
        "Implemented:",
        "",
        "- Automatic retries for transient failures",
        "- Identification and tracking of non-retryable pages",
        "- Error reporting throughout migration lifecycle",
        "",
        "### Controlled Ingestion",
        "",
        "Used Step Functions specifically for page ingestion because CF360 could not be overwhelmed.",
        "",
        "The workflow:",
        "",
        "- Push a batch",
        "- Wait",
        "- Check CF360 health",
        "- Continue only when healthy",
        "- Retry automatically if required",
        "",
        "This is a nice architectural decision because it shows you chose the right tool instead of putting everything into Step Functions.",
        "",
        "### Status Tracking",
        "",
        "Tracked progress across every migration stage.",
        "",
        "Examples include:",
        "",
        "- AEM extraction started",
        "- AEM extraction completed",
        "- Components transformed",
        "- Components pushed",
        "- Components reviewed",
        "- Pages transformed",
        "- Pages ingested",
        "- Failure state with detailed errors",
        "",
        "This gave business users visibility into long-running migrations.",
        ""
      ],
      "html": "<h1>Content Migration Engine</h1>\n<p>Designed and developed a configuration-driven migration platform to migrate content from AEM to CF360 at enterprise scale. Rather than building one-off migration scripts, the platform used runtime-selectable JSON configuration files to support different page structures, templates, and component mappings across multiple migrations.</p>\n<h2>My Ownership</h2>\n<ul>\n<li>End-to-end backend architecture</li>\n<li>AWS Lambda orchestration</li>\n<li>Amazon SQS integration</li>\n<li>AWS Step Functions workflow</li>\n<li>Amazon S3 configuration management</li>\n<li>Migration APIs</li>\n<li>Transformation engine</li>\n<li>Status tracking</li>\n<li>Cloud configuration (excluding VPN/security provisioning handled by DevOps)</li>\n</ul>\n<h2>Key Engineering Decisions</h2>\n<h3>Configuration-driven migrations</h3>\n<p>Migration rules were stored as JSON configuration files in S3 and selected during migration startup.</p>\n<p>This allowed:</p>\n<ul>\n<li>Different migrations to reuse the same engine</li>\n<li>Support for multiple page structures</li>\n<li>Support for different template mappings</li>\n<li>Reduced need for code changes</li>\n</ul>\n<h3>Transformation Engine</h3>\n<p>Handled:</p>\n<ul>\n<li>Field mapping</li>\n<li>Component ID mapping</li>\n<li>Nested list transformations</li>\n<li>Rich text conversion</li>\n<li>Page/component relationship mapping</li>\n<li>Rule-based template detection</li>\n</ul>\n<h3>Scale</h3>\n<ul>\n<li>120,000+ pages</li>\n<li>98 component types</li>\n<li>Batch-based migration pipeline</li>\n</ul>\n<h3>Reliability</h3>\n<p>Implemented:</p>\n<ul>\n<li>Automatic retries for transient failures</li>\n<li>Identification and tracking of non-retryable pages</li>\n<li>Error reporting throughout migration lifecycle</li>\n</ul>\n<h3>Controlled Ingestion</h3>\n<p>Used Step Functions specifically for page ingestion because CF360 could not be overwhelmed.</p>\n<p>The workflow:</p>\n<ul>\n<li>Push a batch</li>\n<li>Wait</li>\n<li>Check CF360 health</li>\n<li>Continue only when healthy</li>\n<li>Retry automatically if required</li>\n</ul>\n<p>This is a nice architectural decision because it shows you chose the right tool instead of putting everything into Step Functions.</p>\n<h3>Status Tracking</h3>\n<p>Tracked progress across every migration stage.</p>\n<p>Examples include:</p>\n<ul>\n<li>AEM extraction started</li>\n<li>AEM extraction completed</li>\n<li>Components transformed</li>\n<li>Components pushed</li>\n<li>Components reviewed</li>\n<li>Pages transformed</li>\n<li>Pages ingested</li>\n<li>Failure state with detailed errors</li>\n</ul>\n<p>This gave business users visibility into long-running migrations.</p>\n",
      "terminal": [
        "$ npm run build -- content-migration-engine",
        "compile... ok",
        "validate... ok",
        "deploy... ok",
        "",
        "stack: aws-lambda step-functions sqs s3 aem cf360",
        "result: 120K+ pages migrated, 98 component types"
      ]
    },
    "projects/run-club.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# Out of Office Run Club",
        "",
        "Production website for a Sunday morning social running community in Kharadi, Pune. Built with Next.js 14 App Router for performance and developer velocity.",
        "",
        "## Architecture",
        "",
        "- **Next.js 14 App Router** — server components for static content, client components for interactive elements (RSVP, calendar)",
        "- **Static generation** — run schedule and route info pre-rendered at build time for instant loading",
        "- **Responsive design** — mobile-first layout optimized for WhatsApp sharing; photo grid with lazy loading",
        "- **Netlify deployment** — instant rollbacks, automatic CI/CD from GitHub, edge caching",
        "",
        "## Pages",
        "",
        "- **Home** — Hero with next-run countdown, club stats, photo gallery, WhatsApp deep-link CTA",
        "- **Schedule** — Run calendar with past/completed badges, current route info, recurring event details",
        "",
        "## Impact",
        "",
        "- 40+ runners at launch through organic community growth",
        "- Bi-weekly 5K social runs with consistent 25+ avg attendance",
        "- Sub-100ms page loads globally (Netlify analytics)",
        "",
        "## Live Site",
        "",
        "https://out-of-office-run-club.netlify.app",
        ""
      ],
      "html": "<h1>Out of Office Run Club</h1>\n<p>Production website for a Sunday morning social running community in Kharadi, Pune. Built with Next.js 14 App Router for performance and developer velocity.</p>\n<h2>Architecture</h2>\n<ul>\n<li><strong>Next.js 14 App Router</strong> — server components for static content, client components for interactive elements (RSVP, calendar)</li>\n<li><strong>Static generation</strong> — run schedule and route info pre-rendered at build time for instant loading</li>\n<li><strong>Responsive design</strong> — mobile-first layout optimized for WhatsApp sharing; photo grid with lazy loading</li>\n<li><strong>Netlify deployment</strong> — instant rollbacks, automatic CI/CD from GitHub, edge caching</li>\n</ul>\n<h2>Pages</h2>\n<ul>\n<li><strong>Home</strong> — Hero with next-run countdown, club stats, photo gallery, WhatsApp deep-link CTA</li>\n<li><strong>Schedule</strong> — Run calendar with past/completed badges, current route info, recurring event details</li>\n</ul>\n<h2>Impact</h2>\n<ul>\n<li>40+ runners at launch through organic community growth</li>\n<li>Bi-weekly 5K social runs with consistent 25+ avg attendance</li>\n<li>Sub-100ms page loads globally (Netlify analytics)</li>\n</ul>\n<h2>Live Site</h2>\n<p><a href=\"https://out-of-office-run-club.netlify.app\">https://out-of-office-run-club.netlify.app</a></p>\n",
      "terminal": [
        "$ npm run build -- run-club",
        "compile... ok",
        "validate... ok",
        "deploy... ok",
        "",
        "stack: nextjs typescript tailwindcss netlify",
        "result: 40+ runners at launch, bi-weekly social runs"
      ]
    },
    "skills.json": {
      "type": "JSON",
      "language": "JSON",
      "code": [
        "{",
        "  \"expertise\": [",
        "    \"Large-scale REST APIs (20M+ Daily Requests)\",",
        "    \"Distributed Systems\",",
        "    \"Serverless Architectures\",",
        "    \"Event-Driven Systems\",",
        "    \"Workflow Orchestration\",",
        "    \"Enterprise Integrations\",",
        "    \"Internal Platform Engineering\",",
        "    \"Operational Tooling & Automation\"",
        "  ],",
        "  \"languages\": [",
        "    \"Python\",",
        "    \"JavaScript\",",
        "    \"TypeScript\",",
        "    \"Go\",",
        "    \"SQL\"",
        "  ],",
        "  \"backend\": [",
        "    \"Node.js\",",
        "    \"Express.js\",",
        "    \"REST APIs\",",
        "    \"Microservices\",",
        "    \"Authentication & SSO\"",
        "  ],",
        "  \"databases\": [",
        "    \"Redis\",",
        "    \"MongoDB\",",
        "    \"OpenSearch\",",
        "    \"SQL\"",
        "  ],",
        "  \"authentication\": [",
        "    \"JWT\",",
        "    \"OAuth\"",
        "  ],",
        "  \"cloud\": {",
        "    \"aws\": [",
        "      \"Lambda\",",
        "      \"Step Functions\",",
        "      \"SQS\",",
        "      \"API Gateway\",",
        "      \"S3\"",
        "    ],",
        "    \"azure\": [",
        "      \"Functions\",",
        "      \"Queues\",",
        "      \"API Management\"",
        "    ]",
        "  },",
        "  \"architecture\": [",
        "    \"Serverless\",",
        "    \"Event-Driven Architecture\",",
        "    \"Workflow Orchestration\",",
        "    \"Cloud-Native Applications\",",
        "    \"Scalable Backend Systems\",",
        "    \"System Integration\"",
        "  ],",
        "  \"caching\": [",
        "    \"Redis\",",
        "    \"CDN Caching\",",
        "    \"Cache Invalidation\",",
        "    \"AEM Dispatcher\"",
        "  ],",
        "  \"contentPlatforms\": [",
        "    \"Adobe Experience Manager (AEM)\",",
        "    \"Akamai CDN\",",
        "    \"NetStorage\"",
        "  ],",
        "  \"observability\": [",
        "    \"ELK Stack\",",
        "    \"New Relic\",",
        "    \"Structured Logging\"",
        "  ],",
        "  \"devops\": [",
        "    \"Git\",",
        "    \"GitHub Actions\",",
        "    \"Swagger / OpenAPI\",",
        "    \"Postman\"",
        "  ],",
        "  \"ai\": [",
        "    \"Claude\",",
        "    \"Copilot CLI\",",
        "    \"OpenCode\",",
        "    \"Ollama\"",
        "  ],",
        "  \"domains\": [",
        "    \"Platform Engineering\",",
        "    \"Enterprise CMS\",",
        "    \"Content Migration\",",
        "    \"Cache Management\",",
        "    \"Workflow Automation\",",
        "    \"AI Agent Workflows\",",
        "    \"Developer Productivity\"",
        "  ]",
        "}"
      ],
      "terminal": [
        "$ jq '.cloud.aws' skills.json",
        "[\"Lambda\", \"Step Functions\", \"SQS\", \"API Gateway\", \"S3\"]",
        "",
        "$ jq '.languages' skills.json",
        "[\"Python\", \"JavaScript\", \"TypeScript\", \"Go\", \"SQL\"]",
        "",
        "$ jq '.expertise' skills.json",
        "[\"Distributed Systems\", \"Serverless Architectures\", \"Event-Driven Systems\", ...]"
      ]
    },
    "contact.md": {
      "type": "Markdown",
      "language": "Markdown",
      "lines": [
        "# Contact",
        "",
        "Phone: +91 9619654093",
        "Email: aadityahemant24@gmail.com",
        "LinkedIn: https://linkedin.com/in/aaditya-hemant",
        "GitHub: https://github.com/aaditya-hemant",
        "[Download Resume](./resume.pdf)",
        "",
        "Open to software engineering, backend, platform, and distributed systems roles."
      ],
      "html": "<h1>Contact</h1>\n<p>Phone: +91 9619654093<br>Email: <a href=\"mailto:aadityahemant24@gmail.com\">aadityahemant24@gmail.com</a><br>LinkedIn: <a href=\"https://linkedin.com/in/aaditya-hemant\">https://linkedin.com/in/aaditya-hemant</a><br>GitHub: <a href=\"https://github.com/aaditya-hemant\">https://github.com/aaditya-hemant</a><br><a href=\"./resume.pdf\">Download Resume</a></p>\n<p>Open to software engineering, backend, platform, and distributed systems roles.</p>\n",
      "terminal": [
        "$ curl /api/contact",
        "HTTP/1.1 200 OK",
        "content-type: application/json",
        "",
        "{",
        "  \"email\": \"aadityahemant24@gmail.com\",",
        "  \"phone\": \"+91 9619654093\",",
        "  \"linkedin\": \"https://linkedin.com/in/aaditya-hemant\",",
        "  \"github\": \"https://github.com/aaditya-hemant\"",
        "}"
      ]
    }
  },
  "commands": {
    "whoami": "about.md",
    "cat about.md": "about.md",
    "git log --oneline": "experience/bajaj-finserv.md",
    "cat experience/bajaj-finserv.md": "experience/bajaj-finserv.md",
    "cat experience/atsuya.md": "experience/atsuya.md",
    "cat education.md": "education.md",
    "ls projects/": "projects/cache-platform.md",
    "cat projects/cache-platform.md": "projects/cache-platform.md",
    "cat projects/ai-cli.md": "projects/ai-cli.md",
    "cat projects/cms-migration.md": "projects/cms-migration.md",
    "cat skills.json": "skills.json",
    "cat contact.md": "contact.md",
    "cat resume.pdf": "contact.md",
    "cat projects/content-migration.md": "projects/content-migration.md",
    "cat projects/run-club.md": "projects/run-club.md"
  }
};